### PR TITLE
Documentation draft

### PR DESCRIPTION
**Pull request by stkurz**
First draft after a couple of hours, the landing page needs refinement, and the rest is quirky, too - I understood most of the concepts and ideas behind what's where, but may have missed some things. Feel free to edit, split, merge and whatever - my Mallard knowledge improved by 100%: which still is not much. 
Also, this is just a stub in terms of implementation (makefiles etc.).

### CODE REVIEW

**Comment by JerryCasiano** [comment]
Whoa! Nice.

I don't have enough time right now, but i just wanted to take a moment to thank you for the time and effort you have put into this so far. Thanks!

I will test this locally over the weekend and get it merged.

**Comment by JerryCasiano** [comment]
BTW, noticed it said that font removal is broken. Will need to remove that.

Font removal works fine or should. It will only allow removal of fonts that were installed by Font Manager or exist in your font folder though. The default folder at this point is ~/.local/share/fonts


Also, forgot that 0.5.7 had documentation in a decent state and some of it may be easy to update. 

https://github.com/FontManager/master/releases/tag/0.5.7

**Comment by stkurz** [comment]
Ok. If I only knew you had that **decent** documentation around – sorry for not poking around in an old release… 
Indeed it makes sense to only let FM remove fonts that it installed; that was not my test case. So it works; just not as I expected (selecting a font in the list and pressing "-" could also preselect that particular font in the list of fonts to delete). Will remove that. 
My approach was quick and dirty from scratch while learning to deal with the app. What do you think makes more sense: a) To take the 0.5.7 docs as a starting point and fill in gaps and check if things changed or b) to start from my sketches and improve from there?

**Comment by JerryCasiano** [comment]
Sorry, I had completely forgotten about it or I would've mentioned it previously.

Completely up to you. You could take whatever works from the previous docs and update them, filling any gaps if you find it easier. I definitely prefer the naming scheme you're using to the old one.

But really whatever works is fine.

Thank you.

**Comment by stkurz** [comment]
Sorry, I was busy with other things - not sure when I'll be able to continue work on this; I'd have to have a look at this on paper, makes more sense in this case to me to have the options really side by side…

**Pull request merged**
