### PR TITLE
Added Russian translation to shortcuts

### PR DESCRIPTION
**Pull request by TotalCaesar659**

### CODE REVIEW

**Comment by JerryCasiano** [comment]
Thank you 

Sorry I haven't merged it sooner, been out of town, will do this weekend.

**Comment by TotalCaesar659** [comment]
Thank you! Could you also accept my Russian translation here by PR, not on https://translate.zanata.org/project/view/font-manager ?
I've registered there, but can't add the translation. I've sent request for accepting me to Russian team, but there is only message "Request pending". And I don't know what to do.
It should be better to place Font Manager translations on Transifex or Crowdin, they are much easier.

**Comment by JerryCasiano** [comment]
Of course. Either way works.

Soon as I get a chance I'll look into why it is still pending.

**Comment by TotalCaesar659** [comment]
OK, here it is https://github.com/FontManager/master/pull/34

**Pull request merged**
